### ISSUE TITLE
Browserify problem / OS X

### ISSUE THREAD

**Issue by szymon-wiatr** [zacol/mirexplayer#1]
In README.md there is no info about generate app.min.js .

In OS X after $npm install  locally I need to change paths to generate app.min.js

window.$ = window.jQuery = require('../../node_modules/jquery');
var angular = require('../../node_modules/angular');
var io = require('../../node_modules/socket.io-client');
var socket = io();
var YouTubeIframeLoader = require('../../node_modules/youtube-iframe');

var app = angular.module('app', [require('../../node_modules/angular-ui-router')]);

and then project start working :)

**Comment by zacol** [comment]
What a shame, I forgot to write some instructions for install and use Mirex Player. I try to do that as soon as possible. At this moment I can write a short manual.

First you need to run `npm install` which install all dependencies.
Next, you need run browserify which pack all scripts into one single file. You could do that from terminal. Go to folder _/public/scripts/_ and run `browserify app.js -o app.min.js`.
Now your application should start without necessity to change paths.

I hope that helps you. I write more soon.

**Comment by zacol** [comment]
I just added installation and configuration section to Readme.
